result/Lösungen/übung_jsf_nav/rent_a_car/src/main/java/de/simplydevelop/hello/NavigationBean.java
package de.simplydevelop.hello;

import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@ConversationScoped
public class NavigationBean implements Serializable{
	
	@Inject
	private Conversation conversation;
	
	@PostConstruct
	public void conversationBegin() {
		conversation.begin();
	}
	
	boolean isDone;

	public NavigationBean() {
		System.out.println("Neue Bean wird erzeugt " + this);
	}

	public boolean isDone() {
		return isDone;
	}

	public void setDone(boolean isDone) {
		System.out.println(this);
		System.out.println("SET IS DONE " + isDone);
		this.isDone = isDone;
	}

	public String back() {
		return "back";
	}
	
	
	public String end() {
		conversation.end();
		return "end";
	}

	public String next() {
		
		System.out.println("NEXT " + isDone);
		return isDone ? Outcome.FINISHED.toString() : Outcome.NOT_FINISHED.toString();
	}
}

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/java/de/simplydevelop/hello/ReservationBean.java
package de.simplydevelop.hello;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import net.jeeschulung.exercise.CarClassification;
import net.jeeschulung.exercise.CarDTO;

@Named
@ConversationScoped
public class ReservationBean implements Serializable {

	@Inject
	private Conversation conversation;
	
	@Inject
	private CarServiceClient carService;

	private String from;

	private String to;

	private String locationName;

	private List<CarClassification> typesToSearch = new ArrayList<CarClassification>();
	
	private CarDTO selected;

	private List<CarDTO> matchingCars;

	private BigDecimal price;
	
	public CarDTO getSelected() {
		return selected;
	}
	
	public List<CarDTO> getMatchingCars() {
		return matchingCars;
	}

	public CarClassification[] getClassifications() {
		return CarClassification.values();
	}

	public Conversation getConversation() {
		return conversation;
	}

	public void setConversation(Conversation conversation) {
		this.conversation = conversation;
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public String getLocationName() {
		return locationName;
	}

	public void setLocationName(String locationName) {
		this.locationName = locationName;
	}

	public List<CarClassification> getTypesToSearch() {
		return typesToSearch;
	}

	public void setTypesToSearch(List<CarClassification> typesToSearch) {
		this.typesToSearch = typesToSearch;
	}

	public String search() {
		if(isNotBlank(from) && isNotBlank(to) && !typesToSearch.isEmpty() && isNotBlank(locationName)) {
			conversation.begin();
			this.matchingCars = carService.findByClassificationAndLocation(typesToSearch, locationName);
			return "successful";
		}
		else
		{
			FacesContext.getCurrentInstance().addMessage(null,new FacesMessage("Nicht alle Eingaben wurden getätigt"));
			return "warning";
		}
	}
	
	public String showSummary() {
		if(this.selected != null) {
			calculatePrice();
			return "successful";
		}
		else
		{
			FacesContext.getCurrentInstance().addMessage(null,new FacesMessage("Wählen Sie ein Fahrzeug aus."));
			return "warning";
		}
	}


	private void calculatePrice() {
		this.price = this.selected.getPrice();
		
	}
	
	public BigDecimal getPrice() {
		return price;
	}

	private boolean isNotBlank(String tocheck) {
		return tocheck != null && !tocheck.isBlank();
	}
	
}

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/cardetail.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:metadata>
    <f:viewParam name="id" value="#{cars.selected}"
                 converter="#{carConverter}" converterMessage="Unknown car, please use a link from within the system."
                 required="true" requiredMessage="Bad request, please use a link from within the system."
    />
   
</f:metadata>
<f:view>
    <h:form id="form">

        <h:panelGrid border="1" columns="2" >
            <h:outputLabel value="Fabrikat" for="brand"></h:outputLabel>
            <h:inputText id="brand" value="#{cars.selected.brand}"></h:inputText>

            <h:outputLabel value="Modell" for="model"></h:outputLabel>
            <h:inputText id="model" value="#{cars.selected.model}"></h:inputText>

            <h:outputLabel value="PS" for="brand"></h:outputLabel>
            <h:inputText id="ps" value="#{cars.selected.hp}"></h:inputText>

            <h:outputLabel value="Max Kmh" for="maxKph"></h:outputLabel>
            <h:inputText id="maxKph" value="#{cars.selected.maxKpH}"></h:inputText>


            <h:outputLabel value="Fahrzeugklasse" for="classification"></h:outputLabel>
            <h:selectManyListbox id="classification" value="#{cars.selected.types}">
                <f:selectItems value="#{cars.classifications}"/>
            </h:selectManyListbox>

            <h:commandButton id="submit" value="Speichern" action="#{cars.saveChanges()}" disabled="#{!cars.hasAdminPermission()}"/>
        </h:panelGrid>
       <h:messages></h:messages>
    </h:form>
</f:view>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/cars.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>

<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
	background-color: #333;
}

li {
	float: left;
}

li a {
	display: block;
	color: white;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

li a:hover:not(.active) {
	background-color: #111;
}

.active {
	background-color: #4CAF50;
}
</style>
</head>
<body>
	<ul>
		<li><a href="cars.xhtml">Autos</a></li>
		<li><a href="locations.xhtml">Filialen</a></li>
		<li><a href="reservation_first.xhtml">Reservierung</a></li>
		<li><a href="#contact">Contact</a></li>
		<li style="float: right"><a class="active" href="#about">About</a></li>
	</ul>
	<f:view>
		<h:dataTable value="#{cars.cars}" var="car" border="1" cellspacing="5">
			<h:column>
				<f:facet name="header">
					<h:outputText value="#{msg['brand']}"></h:outputText>
				</f:facet>
				<h:outputText value="#{car.brand}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Model"></h:outputText>
				</f:facet>
				<h:outputText value="#{car.model}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="PS"></h:outputText>
				</f:facet>
				<h:outputText value="#{car.hp}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="MaxKmh"></h:outputText>
				</f:facet>
				<h:outputText value="#{car.maxKpH}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Aktionen"></h:outputText>
				</f:facet>
				<h:link value="Bearbeiten" outcome="/cardetail">
					<f:param name="id" value="#{car.id}" />
				</h:link>
			</h:column>
		</h:dataTable>
	</f:view>
</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	>
<head>
	<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
	background-color: #333;
}

li {
	float: left;
}

li a {
	display: block;
	color: white;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

li a:hover:not(.active) {
	background-color: #111;
}

.active {
	background-color: #4CAF50;
}
</style>
</head>
<body>
	<ul>
		<li><a href="cars.xhtml">Autos</a></li>
		<li><a href="locations.xhtml">Filialen</a></li>
		<li><a href="reservation_first.xhtml">Reservierung</a></li>
		<li><a href="#contact">Contact</a></li>
		<li style="float: right"><a class="active" href="#about">About</a></li>
	</ul>

</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/locations.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>

<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
	background-color: #333;
}

li {
	float: left;
}

li a {
	display: block;
	color: white;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

li a:hover:not(.active) {
	background-color: #111;
}

.active {
	background-color: #4CAF50;
}
</style>
</head>
<body>
	<ul>
		<li><a href="cars.xhtml">Autos</a></li>
		<li><a href="locations.xhtml">Filialen</a></li>
		<li><a href="reservation_first.xhtml">Reservierung</a></li>
		<li><a href="#contact">Contact</a></li>
		<li style="float: right"><a class="active" href="#about">About</a></li>
	</ul>
	<f:view>
		<h:dataTable value="#{locations.locations}" var="location" border="1"
			cellspacing="5">
			<h:column>
				<f:facet name="header">
					<h:outputText value="Name"></h:outputText>
				</f:facet>
				<h:outputText value="#{location.name}" />
			</h:column>

			<h:column>
				<f:facet name="header">
					<h:outputText value="Place"></h:outputText>
				</f:facet>
				<h:outputText value="#{location.address}" />
			</h:column>



			<h:column>
				<f:facet name="header">
					<h:outputText value="Aktionen"></h:outputText>
				</f:facet>
				<h:link value="Bearbeiten" outcome="/cardetail">
					<f:param name="id" value="#{location.id}" />
				</h:link>
			</h:column>
		</h:dataTable>
	</f:view>
</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/reservation_carselection.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>

<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
	background-color: #333;
}

li {
	float: left;
}

li a {
	display: block;
	color: white;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

li a:hover:not(.active) {
	background-color: #111;
}

.active {
	background-color: #4CAF50;
}
div.form
{
	margin-top: 80px;
    display: block;
    text-align: center;
}
form
{
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    text-align: left;
}
</style>
</head>
<body>
	<ul>
		<li><a href="cars.xhtml">Autos</a></li>
		<li><a href="locations.xhtml">Filialen</a></li>
		<li><a href="reservation_first.xhtml">Reservierung</a></li>
		<li><a href="#contact">Contact</a></li>
		<li style="float: right"><a class="active" href="#about">About</a></li>
	</ul>
	<f:view>
	<div class="form">

		<h:form id="form">
			<h:outputText value="Für ihre Auswahl haben wir folgenden Fahrzeuge gefunden:"></h:outputText>
			<br/>
			<h:selectOneListbox value="#{reservationBean.selected}" converter="#{carConverter}">
				<f:selectItems var="car" itemLabel="#{car.brand.concat(' ').concat(car.model).concat(' ').concat(car.price)}" itemValue="#{car}" value="#{reservationBean.matchingCars}" />
			</h:selectOneListbox>
			<br/>
			<h:commandButton id="submit" value="Fahrzeug übernehmen"
					action="#{reservationBean.showSummary()}" />
			<h:messages></h:messages>
		</h:form>
		</div>
	</f:view>
	
</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/reservation_first.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>

<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
	background-color: #333;
}

li {
	float: left;
}

li a {
	display: block;
	color: white;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

li a:hover:not(.active) {
	background-color: #111;
}

.active {
	background-color: #4CAF50;
}
div.form
{
	margin-top: 80px;
    display: block;
    text-align: center;
}
form
{
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    text-align: left;
}
</style>
</head>
<body>
	<ul>
		<li><a href="cars.xhtml">Autos</a></li>
		<li><a href="locations.xhtml">Filialen</a></li>
		<li><a href="reservation_first.xhtml">Reservierung</a></li>
		<li><a href="#contact">Contact</a></li>
		<li style="float: right"><a class="active" href="#about">About</a></li>
	</ul>
	<f:view>
	<div class="form">
		<h:form id="form">

			<h:panelGrid border="1" columns="2">
				<h:outputLabel value="Von" for="from"></h:outputLabel>
				<h:inputText id="from" value="#{reservationBean.from}"></h:inputText>

				<h:outputLabel value="Bis" for="model"></h:outputLabel>
				<h:inputText id="to" value="#{reservationBean.to}"></h:inputText>

				<h:outputLabel value="Ort" for="brand"></h:outputLabel>
				<h:inputText id="location" value="#{reservationBean.locationName}"></h:inputText>

				<h:outputLabel value="Fahrzeugklasse" for="classification"></h:outputLabel>
				<h:selectManyListbox id="classification"
					value="#{reservationBean.typesToSearch}">
					<f:selectItems value="#{reservationBean.classifications}" />
				</h:selectManyListbox>

				<h:commandButton id="submit" value="Suche"
					action="#{reservationBean.search()}" />
			</h:panelGrid>
			<h:messages></h:messages>
		</h:form>
		</div>
	</f:view>
</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/reservation_summary.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<head>

<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
	background-color: #333;
}

li {
	float: left;
}

li a {
	display: block;
	color: white;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

li a:hover:not(.active) {
	background-color: #111;
}

.active {
	background-color: #4CAF50;
}
div.form
{
	margin-top: 80px;
    display: block;
    text-align: center;
}
form
{
    display: inline-block;
    margin-left: auto;
    margin-right: auto;
    text-align: left;
}
</style>
</head>
<body>
	<ul>
		<li><a href="cars.xhtml">Autos</a></li>
		<li><a href="locations.xhtml">Filialen</a></li>
		<li><a href="reservation_first.xhtml">Reservierung</a></li>
		<li><a href="#contact">Contact</a></li>
		<li style="float: right"><a class="active" href="#about">About</a></li>
	</ul>
	<f:view>
	<div class="form">
		<h:form id="form">
			<h:outputFormat value="Sie wollen {0} für die Zeit von {1} bis {2} reservieren für den Preis von {3}">
				<f:param value="#{reservationBean.selected.brand.concat(' ').reservationBean.selected.model}"></f:param>
				<f:param value="#{reservationBean.from}"></f:param>
				<f:param value="#{reservationBean.to}"></f:param>
				<f:param value="#{reservationBean.price}"></f:param>
			</h:outputFormat>
		</h:form>
		</div>
	</f:view>
	
</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/seitea.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<body>
	<f:view>
		<h:outputText value="Seite A"></h:outputText>
		<h:form>
			<h:selectBooleanCheckbox value="#{navigationBean.done}"></h:selectBooleanCheckbox>
		
			<h:commandButton value="Next" action="#{navigationBean.next()}"></h:commandButton>
		</h:form>
		
	</f:view>
</body>
</html>

result/Lösungen/übung_jsf_nav/rent_a_car/src/main/webapp/seiteb.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<body>
	<f:view>
		<h:outputText value="Seite B"></h:outputText>
		<h:form>
			<h:commandButton value="Back" action="#{navigationBean.back()}"></h:commandButton>
			<h:commandButton value="End" action="#{navigationBean.end()}"></h:commandButton>
		</h:form>
		
	</f:view>
</body>
</html>